---
resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/generators/0/git/directories
        value:
          - path: 'argo/*/env/nyc'
    target:
      kind: ApplicationSet
      name: root
      namespace: argocd
